title: zhaoch-wei的博客
author: zhaoch-wei
email: zhaoch_wei@163.com
description: > # this means to ignore newlines until "baseurl:"
  学习在于积累，积累始于记录

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minina
